root: ./

​structure:
  readme: README.md
  summary: SUMMARY.md​

redirects:
  enterprise/installation: enterprise/installation/README.md
  enterprise/installation/: enterprise/installation/README.md
  enterprise/post-installation: enterprise/post-installation/README.md
  enterprise/post-installation/: enterprise/post-installation/README.md
  ann_format: data-organization/supervisely-format.md
  ann_format/: data-organization/supervisely-format.md
